# Configuration file for ForbiddenBlocks version 1.1 plugin

#Message Formatting
#Colors: <red>, </red>, <green>, </green>, <blue>, </blue>, <gold>, </gold>, <aqua>, </aqua> etc.
#Bold: <bold>This is bold</bold>
#Italic: <italic>This is italic</italic>
#Underline: <underlined>This is underlined</underlined>
#Strikethrough: <strikethrough>This is struck through</strikethrough>
#Gradient: <gradient:red:blue>Gradient Text</gradient>
#Rainbow: <rainbow>Rainbow Text</rainbow>

messages:
  noPermission: <red>You don't have permission to use this command.</red>
  mustHoldNamedItem: <bold><rainbow>You must hold an item with a display name.</rainbow></bold>
  itemForbidden: <strikethrough><gold>This item is now forbidden to be placed.</gold></strikethrough>
  itemAllowed: <italic><gradient:aqua:blue>This item is now allowed to be placed.</gradient></italic>
  cannotPlace: <underlined><gradient:gold:red>You cannot place this item!</gradient></underlined>

options:
  sendMessages: true # Toggle this to enable/disable messages.

forbiddenItems: []
