name: ForbiddenBlocks
version: '1.0'
main: me.lucievol.noPlaceBlock.noPlaceBlock
api: '1.21'
commands:
  forbiditem:
    description: Forbids the placement of an item.
    usage: /forbiditem
    permission: no_placeblock.forbid
  allowitem:
    description: Allows the placement of an item.
    usage: /allowitem
    permission: no_placeblock.allow
  togglemessages:
    description: Toggles placement restriction messages.
    usage: /togglemessages
    permission: no_placeblock.togglemessages
  listforbidden:
    description: Lists all forbidden items.
    usage: /listforbidden
    permission: no_placeblock.list
  reloadconfig:
    description: Reloads the configuration file.
    usage: /reloadconfig
    permission: no_placeblock.reload
permissions:
  forbiddenblocks.forbid:
    description: Allows player to forbid items from being placed.
    default: op
  forbiddenblocks.allow:
    description: Allows player to allow previously forbidden items to be placed.
    default: op
  forbiddenblocks.togglemessages:
    description: Allows player to toggle block placement messages.
    default: op
  forbiddenblocks.list:
    description: Allows player to list all forbidden items.
    default: op
  forbiddenblocks.reload:
    description: Allows player to reload the configuration.
    default: op
